services:
  - type: web
    name: moodsnap-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 5001

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: FRONTEND_URL
        value: http://localhost:8081
