import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/colors";

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 62,
    paddingBottom: 120,
  },
  handle: {
    alignSelf: "center",
    width: 44,
    height: 6,
    borderRadius: 99,
    backgroundColor: "#555",
    marginBottom: 30,
  },
  profileHeader: {
    alignItems: "center",
    marginBottom: 30,
  },
  avatarOuter: {
    width: 126,
    height: 126,
    borderRadius: 63,
    borderWidth: 6,
    borderColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
  },
  avatarInner: {
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: "#2b2b2b",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.62)",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarOverlayText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "900",
  },
  avatarInitial: {
    color: "#fff",
    fontSize: 44,
    fontWeight: "900",
  },
  name: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "900",
  },
  link: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "900",
    marginTop: 8,
    textAlign: "center",
    backgroundColor: "rgba(246,80,120,0.12)",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    overflow: "hidden",
  },
  quickRow: {
    flexDirection: "row",
    gap: 14,
    marginTop: 24,
  },
  quickButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#3a3a3a",
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 28,
    minWidth: 132,
    justifyContent: "center",
  },
  quickIcon: {
    fontSize: 14,
  },
  quickText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "900",
  },
  sectionWrap: {
    marginTop: 22,
  },
  sectionTitle: {
    color: "#bdbdbd",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 12,
    marginLeft: 8,
  },
  sectionCard: {
    backgroundColor: "#3a3a3a",
    borderRadius: 24,
    overflow: "hidden",
    paddingVertical: 8,
  },
  row: {
    minHeight: 58,
    paddingHorizontal: 18,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  rowIcon: {
    width: 34,
    textAlign: "center",
    color: "#fff",
    fontSize: 21,
    fontWeight: "900",
  },
  rowLabel: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "900",
  },
  chevron: {
    color: "#777",
    fontSize: 34,
    fontWeight: "500",
    marginTop: -4,
  },
  dangerText: {
    color: "#ff4d4d",
  },
  footer: {
    color: "#7a7a7a",
    textAlign: "center",
    marginTop: 34,
    fontSize: 13,
    fontWeight: "800",
  },
  requestRow: {
    minHeight: 72,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  requestName: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
  },
  requestMeta: {
    color: "#aaa",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  requestActions: {
    flexDirection: "row",
    gap: 8,
  },
  rejectButton: {
    borderRadius: 14,
    backgroundColor: "#292929",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  rejectText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 12,
  },
  acceptButton: {
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  acceptText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.78)",
    justifyContent: "center",
    padding: 22,
  },
  modalCard: {
    backgroundColor: "#151515",
    borderRadius: 28,
    padding: 20,
  },
  modalTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 14,
  },
  modalBody: {
    color: "#aaa",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
  },
  nameInput: {
    backgroundColor: "#222",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#fff",
    fontSize: 18,
    fontWeight: "800",
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  cancelButton: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 14,
    backgroundColor: "#292929",
    alignItems: "center",
  },
  cancelText: {
    color: "#fff",
    fontWeight: "900",
  },
  fullCancelButton: {
    borderRadius: 18,
    paddingVertical: 14,
    backgroundColor: "#292929",
    alignItems: "center",
    marginTop: 18,
  },
  saveButton: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  saveText: {
    color: "#fff",
    fontWeight: "900",
  },
  doneButton: {
    borderRadius: 18,
    paddingVertical: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  colorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 8,
  },
  colorCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: "transparent",
  },
  colorCircleSelected: {
    borderColor: "#fff",
    transform: [{ scale: 1.08 }],
  },
  starRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 18,
  },
  starButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#242424",
  },
  starText: {
    color: "#777",
    fontSize: 30,
    fontWeight: "900",
  },
  starTextSelected: {
    color: COLORS.primary,
  },
  termsCard: {
    backgroundColor: "#151515",
    borderRadius: 28,
    padding: 20,
    maxHeight: "82%",
  },
  termsScroll: {
    marginBottom: 18,
  },
  termsText: {
    color: "#d9d9d9",
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 22,
    marginBottom: 14,
  },
  friendsModalCard: {
    backgroundColor: "#151515",
    borderRadius: 28,
    padding: 20,
    maxHeight: "78%",
  },
  friendsModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#292929",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "900",
  },
  friendsList: {
    maxHeight: 430,
  },
  friendsSectionTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "900",
    marginTop: 8,
    marginBottom: 4,
  },
  retryBox: {
    alignItems: "flex-start",
    gap: 10,
  },
  friendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#252525",
  },
  friendAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#2b2b2b",
    borderWidth: 2,
    borderColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  friendAvatarImage: {
    width: "100%",
    height: "100%",
  },
  friendAvatarInitial: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "900",
  },
  friendInfo: {
    flex: 1,
  },
  friendName: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "900",
  },
  friendMeta: {
    color: "#aaa",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  friendActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  reportButton: {
    borderRadius: 14,
    backgroundColor: "#2a1118",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  reportText: {
    color: "#ff6b8a",
    fontWeight: "900",
    fontSize: 12,
  },
  friendsEmptyText: {
    color: "#aaa",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 22,
    paddingVertical: 18,
  },
  addFriendBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 4,
    marginBottom: 14,
  },
  addFriendInput: {
    flex: 1,
    backgroundColor: "#222",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    borderWidth: 1,
    borderColor: "#333",
  },
  addFriendButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  addFriendButtonText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 13,
  },
  disabledButton: {
    opacity: 0.6,
  },
});

export const withAlpha = (hex, alpha = "22") => {
  if (typeof hex !== "string" || !hex.startsWith("#") || hex.length !== 7) {
    return "rgba(246,80,120,0.14)";
  }

  return `${hex}${alpha}`;
};

export const colorOptions = [
  "#F65078",
  "#FF8A00",
  "#FFD166",
  "#06D6A0",
  "#118AB2",
  "#7B61FF",
  "#FF4FD8",
  "#FFFFFF",
];
